---
multicast:
    app: multicast
    bind_ip: 127.0.0.1
    bind_port: 20000
    pidfile: /var/run/multicast.pid
    defaults:
        group: 225.0.0.250
        port: 13310
        ttl: 5
        node_id: '1001'
        repeat: 3
        iface: eth0
        timeout: 10
