---
multicast:
    app: multicast
    pidfile: /var/run/multicast.pid
    unix: /var/run/multicast.sock
    defaults:
        group: 225.0.0.250
        port: 13310
        ttl: 5
        node_id: '1001'
        repeat: 3
        iface: eth0
        timeout: 10
