"""plugin_storage

Revision ID: 10c2da372fe0
Revises: 1a1504d469f8
Create Date: 2014-06-02 15:26:39.263073

"""

# revision identifiers, used by Alembic.
revision = '10c2da372fe0'
down_revision = '1a1504d469f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plugin_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plugin', sa.String(length=150), nullable=True),
        sa.Column('record_type', sa.Enum(
            'role',
            'pending_role',
            'volume',
            name='record_type'
        ), nullable=False),
        sa.Column('data', postgresql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_records')
    ### end Alembic commands ###
