#    Copyright 2015 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""empty message

Revision ID: 1baac34bc0c0
Revises: 37608259013
Create Date: 2015-05-22 15:23:23.904246

"""

# revision identifiers, used by Alembic.
revision = '1baac34bc0c0'
down_revision = '37608259013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'network_groups', 'nodegroups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'nodes', 'nodegroups', ['group_id'], ['id'])
    op.alter_column('oswl_stats', 'resource_checksum',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'oswl_stats', ['cluster_id', 'created_date', 'resource_type'])
    op.add_column('plugins', sa.Column('ui', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'ui')
    op.drop_constraint(None, 'oswl_stats', type_='unique')
    op.alter_column('oswl_stats', 'resource_checksum',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'network_groups', type_='foreignkey')
    ### end Alembic commands ###
