"""Re-use DHCP ip as admin IP

Revision ID: 30fe3a6d3a02
Revises: 4f21f21e2672
Create Date: 2014-04-11 14:53:15.996954

"""

# revision identifiers, used by Alembic.
revision = '30fe3a6d3a02'
down_revision = '4f21f21e2672'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    ### end Alembic commands ###
