"""Add NodeGroup

Revision ID: 330ec2ab2bbf
Revises: 4f21f21e2672
Create Date: 2014-03-18 12:58:04.432181

"""

# revision identifiers, used by Alembic.
revision = '330ec2ab2bbf'
down_revision = '4f21f21e2672'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nodegroups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cluster_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'clusters', ['name'])
    op.add_column(
        u'network_groups',
        sa.Column('group_id', sa.Integer(), nullable=True)
    )
    op.add_column(u'nodes', sa.Column('group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'nodes', 'group_id')
    op.drop_column(u'network_groups', 'group_id')
    op.drop_constraint(None, 'clusters')
    op.create_index('clusters_name_key', 'clusters', [u'name'], unique=True)
    op.drop_table('nodegroups')
    ### end Alembic commands ###
