#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""empty message

Revision ID: 34282fd48802
Revises: 1b1d4016375d
Create Date: 2014-11-26 15:07:07.651354

"""

# revision identifiers, used by Alembic.
revision = '34282fd48802'
down_revision = '1b1d4016375d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_roles', sa.Column('primary', sa.Boolean(), nullable=True))
    op.add_column('pending_node_roles', sa.Column('primary', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_node_roles', 'primary')
    op.drop_column('node_roles', 'primary')
    ### end Alembic commands ###
