#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""empty message

Revision ID: 401b7df290c0
Revises: 1b1d4016375d
Create Date: 2014-11-24 13:55:02.877801

"""

# revision identifiers, used by Alembic.
revision = '401b7df290c0'
down_revision = '1b1d4016375d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('primary', sa.Boolean(), nullable=False))
    op.drop_constraint(u'roles_name_release_id_key', 'roles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        u'roles_name_release_id_key', 'roles', ['name', 'release_id'])
    op.drop_column('roles', 'primary')
    ### end Alembic commands ###
