#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""empty message

Revision ID: 4399138f9bfd
Revises: 1b1d4016375d
Create Date: 2014-10-14 19:02:52.546032

"""

# revision identifiers, used by Alembic.
revision = '4399138f9bfd'
down_revision = '1b1d4016375d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plugins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('version', sa.String(length=32), nullable=True),
        sa.Column('description', sa.String(length=400), nullable=True),
        sa.Column('releases', postgresql.JSON(), nullable=True),
        sa.Column('types', postgresql.JSON(), nullable=True),
        sa.Column('package_version', sa.String(length=32), nullable=True),
        sa.Column('depends_on_plugin', postgresql.JSON(), nullable=True),
        sa.Column('conflicts', postgresql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'cluster_plugins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cluster_id', sa.Integer(), nullable=True),
        sa.Column('plugin_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['cluster_id'], ['plugins.id'], ),
        sa.ForeignKeyConstraint(['plugin_id'], ['clusters.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_plugins')
    op.drop_table('plugins')
    ### end Alembic commands ###
