"""patching_of_openstack

Revision ID: 45e649ec488e
Revises: 4f21f21e2672
Create Date: 2014-04-09 10:55:20.660939

"""

# revision identifiers, used by Alembic.
revision = '45e649ec488e'
down_revision = '4f21f21e2672'

from alembic import op
import sqlalchemy as sa

from nailgun.db.sqlalchemy.models.fields import JSON


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters',
                  sa.Column('current_release_id',
                            sa.Integer(),
                            nullable=False))
    # op.add_column('clusters',
    # sa.Column('pending_release_id', sa.Integer(), nullable=True))
    op.drop_column('clusters', 'release_id')

    op.add_column('releases',
                  sa.Column('can_update_os_versions',
                            JSON(),
                            nullable=True))
    op.add_column('releases',
                  sa.Column('compatible_fuel_versions',
                            JSON(),
                            nullable=True))
    op.add_column('releases',
                  sa.Column('current_os_version',
                            sa.String(length=30),
                            nullable=False))
    op.add_column('releases',
                  sa.Column('pp_manifests_source',
                            sa.Unicode(length=255),
                            nullable=True))
    op.add_column('releases',
                  sa.Column('pp_modules_source',
                            sa.Unicode(length=255),
                            nullable=True))
    op.add_column('releases',
                  sa.Column('repo_source',
                            sa.Unicode(length=255),
                            nullable=True))
    op.drop_column('releases', 'version')
    op.create_unique_constraint(None,
                                'releases',
                                ['name', 'current_os_version'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases',
                  sa.Column('version',
                            sa.VARCHAR(length=30),
                            nullable=False))
    op.drop_column('releases', 'repo_source')
    op.drop_column('releases', 'pp_modules_source')
    op.drop_column('releases', 'pp_manifests_source')
    op.drop_column('releases', 'current_os_version')
    op.drop_column('releases', 'compatible_fuel_versions')
    op.drop_column('releases', 'can_update_os_versions')

    op.add_column('clusters',
                  sa.Column('release_id',
                            sa.INTEGER(),
                            nullable=False))
    # op.drop_column('clusters', 'pending_release_id')
    op.drop_column('clusters', 'current_release_id')
    op.create_unique_constraint(None,
                                'releases',
                                ['name', 'version'])
    ### end Alembic commands ###
