#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""empty message

Revision ID: 4beafd17af58
Revises: 1b1d4016375d
Create Date: 2014-11-25 16:00:12.354114

"""

# revision identifiers, used by Alembic.
revision = '4beafd17af58'
down_revision = '1b1d4016375d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'primary_node_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Integer(), nullable=True),
        sa.Column('node', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['node'], ['nodes.id'], ),
        sa.ForeignKeyConstraint(['role'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primary_node_roles')
    ### end Alembic commands ###
