"""Changes before merge

Revision ID: 4f21f21e2672
Revises: 58c8dbea159d
Create Date: 2014-02-12 18:16:55.630914

"""

# revision identifiers, used by Alembic.
revision = '4f21f21e2672'
down_revision = '58c8dbea159d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from nailgun.db.sqlalchemy.models.fields import JSON


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugins')
    op.drop_table('allowed_networks')
    op.add_column(
        'network_groups',
        sa.Column('meta', JSON(), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_groups', 'meta')
    op.create_table(
        'allowed_networks',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default="nextval('allowed_networks_id_seq'::regclass)",
            nullable=False
        ),
        sa.Column(
            'network_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'interface_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['interface_id'],
            [u'node_nic_interfaces.id'],
            name=u'allowed_networks_interface_id_fkey',
            ondelete=u'CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['network_id'],
            [u'network_groups.id'],
            name=u'allowed_networks_network_id_fkey',
            ondelete=u'CASCADE'
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name=u'allowed_networks_pkey'
        )
    )
    op.create_table(
        'plugins',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default="nextval('plugins_id_seq'::regclass)",
            nullable=False
        ),
        sa.Column(
            'type',
            postgresql.ENUM(u'nailgun', u'fuel', name='plugin_type'),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'name',
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'state',
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'version',
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=u'plugins_pkey')
    )
    ### end Alembic commands ###
