"""global parameters removed

Revision ID: 58c8dbea159d
Revises: 3540e7a3ba1e
Create Date: 2014-01-31 19:42:20.485546

"""

# revision identifiers, used by Alembic.
revision = '58c8dbea159d'
down_revision = '3540e7a3ba1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_parameters')
    op.alter_column(
        'network_groups',
        'netmask',
        existing_type=sa.VARCHAR(length=25),
        nullable=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'network_groups',
        'netmask',
        existing_type=sa.VARCHAR(length=25),
        nullable=False
    )
    op.create_table(
        'global_parameters',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default="nextval('global_parameters_id_seq'::regclass)",
            nullable=False
        ),
        sa.Column(
            'parameters',
            sa.TEXT(),
            autoincrement=False,
            nullable=True
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name=u'global_parameters_pkey'
        )
    )
    ### end Alembic commands ###
