"""empty message

Revision ID: 95b33877602
Revises: 58c8dbea159d
Create Date: 2014-02-03 19:44:27.443033

"""

# revision identifiers, used by Alembic.
revision = '95b33877602'
down_revision = '58c8dbea159d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column(
        'cached', sa.String(length=40), nullable=True
    ))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'cached')
    ### end Alembic commands ###
