"""fuel_5_1

Revision ID: 52924111f7d8
Revises: 1398619bdf8c
Create Date: 2014-06-09 13:25:25.773543

"""

# revision identifiers, used by Alembic.
revision = '52924111f7d8'
down_revision = '1398619bdf8c'

from nailgun import consts
from nailgun.utils.migration import upgrade_enum

cluster_changes_old = (
    'networks',
    'attributes',
    'disks'
)
cluster_changes_new = consts.CLUSTER_CHANGES


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    upgrade_enum(
        "cluster_changes",          # table
        "name",                     # column
        "possible_changes",         # ENUM name
        cluster_changes_old,        # old options
        cluster_changes_new         # new options
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    upgrade_enum(
        "cluster_changes",          # table
        "name",                     # column
        "possible_changes",         # ENUM name
        cluster_changes_new,        # new options
        cluster_changes_old,        # old options
    )
    ### end Alembic commands ###
