name: "fuel_agent_ci"
envdir: "/var/tmp/fuel_agent_ci"

net:
  - name: "net"
    ip: "10.250.2.1"
    bridge: "ci"
    forward: "nat"

vm:
  - name: "vm"
    interfaces:
      - mac: "52:54:a5:45:65:ae"
        network: "net"
    disks:
      - size: "10240"
    boot: "network"

ssh:
  - name: "vm"
    host: "10.250.2.20"
    user: "root"
    key_filename: "ssh/id_rsa"

repo:
  - name: "fuel_agent"
    url: "https://github.com/stackforge/fuel-web.git"
    branch: "master"
    path: "fuel_agent"

artifact:
  - name: "tftpboot"
    url: "http://desktop:9090/tftpboot.tgz"
    path: "tftpboot.tgz"
    unpack: "tar zxf tftpboot.tgz"
    clean: "rm -rf tftpboot tftpboot.tgz"
  - name: "image"
    url: "http://desktop:9090/image.tgz"
    path: "image.tgz"
    unpack: "tar zxf image.tgz"
    clean: "rm -rf image image.tgz"
  - name: "ssh"
    url: "http://desktop:9090/ssh.tgz"
    path: "ssh.tgz"
    unpack: "tar zxf ssh.tgz"
    clean: "rm -rf ssh ssh.tgz"

dhcp:
  - name: "dhcp"
    begin: "10.250.2.2"
    end: "10.250.2.254"
    hosts:
      - mac: "52:54:a5:45:65:ae"
        ip: "10.250.2.20"
        name: "fuel-agent-ci.domain.tld"
    bootp:
      file: "pxelinux.0"
    network: "net"

tftp:
  - name: "tftp"
    tftp_root: "tftpboot"
    network: "net"

http:
  - name: "http"
    port: "8888"
    http_root: "image"
    network: "net"
