# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 348]
  end

  config.vm.define :develop do |config|
    # this is hack to make 2 interfaces in same l2 network
    config.vm.network :private_network, ip: '192.168.10.2', type: "dhcp"
    config.vm.network :private_network, ip: '192.168.10.4'
    config.vm.provision :shell, :inline => "echo 'deb http://fuel-repository.mirantis.com/fwm/5.0/ubuntu precise main' >> /etc/apt/sources.list"
    config.vm.provision :shell, :inline => "sudo apt-get update"
    config.vm.provision :shell, :inline => "sudo apt-get -y --force-yes install cliff-tablib python-pyparsing python-pypcap scapy python-pip"
    config.vm.provision :shell, :inline => "sudo pip install pytest mock"
    config.vm.provision :shell, :inline => "cd /vagrant && sudo python setup.py develop"
  end

end
